# Rename this file to config.yaml
# D&D Beyond settings
character_directory: dnd_beyond/characters
characters:
  - name: Wizard
    discord_username: Tom
    id: 000000000 
dndbeyond: 
  character_service_url: https://character-service.dndbeyond.com/character/v3/character/
# Discord bot settings
# Obtain token from https://discord.com/developers/applications
discord:
  token:
database:
  user: dm
  password: 
  database: sidequests
  host: localhost
