CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS players;
CREATE TABLE players (
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE,
    username VARCHAR(255),
    joined_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    op BOOLEAN DEFAULT FALSE,
    email VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    activated BOOLEAN DEFAULT TRUE,
    current_character_id INTEGER
);

DROP TABLE IF EXISTS characters;
CREATE TABLE characters (
    id SERIAL PRIMARY KEY,
    player_uuid UUID NOT NULL,
    create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    dnd_beyond_id INTEGER,
    name VARCHAR(255),
    age INTEGER,
    race VARCHAR(100),
    faith VARCHAR(100),
    hair VARCHAR(50),
    eyes VARCHAR(50),
    skin VARCHAR(50),
    height VARCHAR(32),
    weight INTEGER,
    armor_class INTEGER,
    initiative INTEGER,
    walking_speed INTEGER,
    base_hit_points INTEGER,
    current_xp INTEGER DEFAULT 0,
    lifestyle_id INTEGER,
    strength INTEGER,
    dexterity INTEGER,
    constitution INTEGER,
    intelligence INTEGER,
    wisdom INTEGER,
    charisma INTEGER,
    acrobatics INTEGER,
    animal_handling INTEGER,
    arcana INTEGER,
    athletics INTEGER,
    deception INTEGER,
    history INTEGER,
    insight INTEGER,
    intimidation INTEGER,
    investivation INTEGER,
    medicine INTEGER,
    nature INTEGER,
    perception INTEGER,
    performance INTEGER,
    persuasion INTEGER,
    religion INTEGER,
    sleight_of_hand INTEGER,
    stealth INTEGER,
    survival INTEGER,
    inspiration BOOLEAN DEFAULT FALSE,
    bonus_hit_points INTEGER DEFAULT 0,
    temporary_hit_points INTEGER DEFAULT 0,
    platinum_amount DECIMAL(10, 2),
    gold_amount DECIMAL(10, 2),
    electrum_amount DECIMAL(10, 2),
    silver_amount DECIMAL(10, 2),
    copper_amount DECIMAL(10, 2)
);
